name = "backend"
compatibility_date = "2024-08-15"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmQwMDA2ODMtMzkxZS00NGVjLWEzOGMtYWQ2YmU3YzllYjUyIiwidGVuYW50X2lkIjoiOTc2MmEyZGJjNTIyNzkzNzUxNWE1YzhiZmZjYjY4NzQ2ZjhlNGUxNjA4MWZmMjNkNTYzZTA4ZDY2ZGE4ODE0NCIsImludGVybmFsX3NlY3JldCI6IjkzODFlODU2LTMxZWYtNGIzZS1hM2Y4LWMyOThjMWFkNDg1ZSJ9.CJelFrl5wVCAHGwrkRVqKi997BVPl6WVwb_7A1sasDE"
JWT_SECRET="ASDADDADS"



# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"